-- Step 1: CCSID_TEST テーブル作成 + CDC 有効化
-- 推奨: MODE=setup ./run_step1_on_ec2.sh（再実行可能・エラー処理込み）
-- 手動実行時は REMOVETABLE → DROP → CREATE → ADDTABLE → reinit の順

CONNECT TO TESTDB;

-- 既存 CDC 登録を解除（未登録の場合はエラーになることがある）
CALL ASNCDC.REMOVETABLE('DB2INST1', 'CCSID_TEST');

DROP TABLE IF EXISTS DB2INST1.CCSID_TEST;

CREATE TABLE DB2INST1.CCSID_TEST (
    ID          INT NOT NULL PRIMARY KEY,
    REGION      VARCHAR(10),
    NAME_COL    VARCHAR(100),
    PROBLEM_COL VARCHAR(500)
);

CALL ASNCDC.ADDTABLE('DB2INST1', 'CCSID_TEST');

VALUES ASNCDC.ASNCDCSERVICES('reinit', 'asncdc');

-- LUW では DATA_CAPTURE 列は存在しない — IBMSNAP_REGISTER で確認
SELECT SOURCE_OWNER, SOURCE_TABLE, CD_OWNER, CD_TABLE
FROM ASNCDC.IBMSNAP_REGISTER
WHERE SOURCE_OWNER = 'DB2INST1' AND SOURCE_TABLE = 'CCSID_TEST';
