DELETE FROM DB2INST1.CCSID_TEST WHERE ID >= 9000;

INSERT INTO DB2INST1.CCSID_TEST VALUES (9001, 'JPN', '日本語テスト', '混合文字列：日本語・English・123');
INSERT INTO DB2INST1.CCSID_TEST VALUES (9002, 'SYZ', '中文测试', '简体中文混合测试');
INSERT INTO DB2INST1.CCSID_TEST VALUES (9003, 'KOR', '한국어테스트', '한글 혼합 테스트');
INSERT INTO DB2INST1.CCSID_TEST VALUES (9004, 'DEU', 'Deutsch Test', 'Grüße aus München');
INSERT INTO DB2INST1.CCSID_TEST VALUES (9005, 'TUR', 'İstanbul', 'Türkçe karakter: ğüşıöç');
INSERT INTO DB2INST1.CCSID_TEST VALUES (9006, 'USA', 'Hello World', 'English mixed 123');

SELECT ID, REGION, NAME_COL, PROBLEM_COL FROM DB2INST1.CCSID_TEST WHERE ID >= 9000 ORDER BY ID;
