DELETE FROM DB2INST1.CCSID_TEST WHERE ID = 9100;
INSERT INTO DB2INST1.CCSID_TEST VALUES (9100, 'SYZ', '中文测试', 'INSERT確認');
UPDATE DB2INST1.CCSID_TEST SET PROBLEM_COL = 'UPDATE確認' WHERE ID = 9100;
DELETE FROM DB2INST1.CCSID_TEST WHERE ID = 9100;
